<user.format_text>$: insert(format_text)
phrase <phrase>$: dictate.lower(phrase)
phrase <phrase> (done | over): dictate.lower(phrase)
(say | speak) <phrase>$: dictate.lower(phrase)
word <word>: dictate.lower(word)
