(new window | open new): app.window_open()
next window: app.window_next()
last window: app.window_previous()
close (window | file | tab): app.window_close()
focus <user.running_applications>: user.switcher_focus(running_applications)
[toggle] desktop: key(fn-f11)